export const egeData = [
    "JavaScript", 
    "Python", 
    "Java", 
    "C#", 
    "PHP", 
    "TypeScript", 
    "Ruby", 
    "Go", 
    "Swift", 
    "Rust", 
    "React", 
    "Vue.js", 
    "Angular", 
    "Svelte", 
    "Node.js", 
    "Django", 
    "Flask", 
    "Spring Boot", 
    "Ruby on Rails", 
    "ASP.NET", 
    "Jest", 
    "Mocha", 
    "Selenium", 
    "JUnit", 
    "pytest", 
    "Cypress", 
    "TestNG", 
    "Postman", 
    "Katalon Studio", 
    "Robot Framework"
];